import { Plus_Jakarta_Sans } from 'next/font/google';
import '@styles/global.css';
import Navbar from '@components/navbar/navbar.js';

const jakarta_sans = Plus_Jakarta_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jakarta_sans.className}>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
